version: 2.1

orbs:
  python: circleci/python@0.2.1
  win: circleci/windows@2.2.0

jobs:
  build-and-test:
    executor: python/default
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - run:
          command: pip3 install -r requirements.txt
          name: Install dependencies
      - run:
          command: pip3 install flake8 pytest pydocstyle
          name: Install flake8 and pytest
      - python/save-cache
      - run:
          command: python3 -m flake8 .
          name: flake8 checks
      - run:
          command: python3 -m pydocstyle numpy ave/
          name: pydocstyle checks
      - run:
          command: sudo python3 setup.py install
          name: Install AVE
      - run:
          command: python3 -m pytest test/
          name: Run tests

  build-windows:
    executor: win/default
    steps:
        - checkout
        - run:
            command: py -m pip install .
            name: Install AVE
        - run:
            command: py -m pytest test
            name: Run tests

workflows:
  main:
    jobs:
      - build-and-test
      - build-windows
